import './globals.css';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import icon from '@/public/icon/castella/icon.png';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className + " overflow-hidden"}>
        <Header />
        {children}
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className='flex h-20  items-center  bg-primary shadow-md'>
      <Image className='ml-5' src={icon} width={56} height={56} alt='icon' />
      <div className='ml-1 text-white text-2xl indent-2 font-zenkaku tracking-widest'>かすていら</div>
    </header>
  );
}
