import './globals.css';
import { Inter } from 'next/font/google';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}

function Header() {
  return <header className='h-16 bg-primary shadow-md'>
    <Image src='/icon/castella/icon.png' width={64} height={64}/>
      </header>;{}
}